name: 'Semantic A11y Context Checker'
description: 'Audits code for semantic and contextual WCAG violations'
author: 'Annika Chan'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN to allow posting PR comments'
    required: false
runs:
  using: 'node24'
  main: 'dist/index.js'